"""v2 baseline schema

Revision ID: ff0494d73eb6
Revises: 
Create Date: 2026-06-04 15:15:25.706981
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0494d73eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_titles_id'), 'job_titles', ['id'], unique=False)
    op.create_index(op.f('ix_job_titles_name'), 'job_titles', ['name'], unique=True)
    op.create_table('shift_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='e.g. A, B, C, P/N'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False, comment='Paid duration in hours (handles midnight crossing)'),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_types_code'), 'shift_types', ['code'], unique=True)
    op.create_index(op.f('ix_shift_types_id'), 'shift_types', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Short code e.g. ME-I, ME-II'),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'HR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=False, comment='Role, e.g. doctor, admin, OSS — drives substitution'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='Contract location (e.g. Location X)'),
    sa.Column('contract_type', sa.Enum('PART_TIME', 'FULL_TIME', name='contracttype'), nullable=False),
    sa.Column('monthly_hour_limit', sa.Float(), nullable=False, comment='Contractual parameter hours per month (e.g. 104.28 / 130.35)'),
    sa.Column('flexible_shift', sa.Boolean(), nullable=False, comment='Rotates morning<->afternoon weekly'),
    sa.Column('flexible_location', sa.Boolean(), nullable=False, comment='Rotates between locations weekly'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_codice_fiscale'), 'employees', ['codice_fiscale'], unique=True)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_site_id'), 'employees', ['site_id'], unique=False)
    op.create_table('employee_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('coverable_role', sa.String(length=100), nullable=False, comment='An additional job_title this employee may cover'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'coverable_role', name='uq_employee_coverable_role')
    )
    op.create_index(op.f('ix_employee_coverage_employee_id'), 'employee_coverage', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_coverage_id'), 'employee_coverage', ['id'], unique=False)
    op.create_table('roster_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=True),
    sa.Column('absence_code', sa.Enum('VACATION', 'SICK_LEAVE', 'TEMP_TRANSFER', 'FIXED_SUB', 'VARIABLE_SUB', 'SOLIDARITY', name='absencecode'), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('substitutes_for_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['substitutes_for_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_employee_workdate')
    )
    op.create_index(op.f('ix_roster_assignments_employee_id'), 'roster_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_roster_assignments_id'), 'roster_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_roster_assignments_work_date'), 'roster_assignments', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_assignments_work_date'), table_name='roster_assignments')
    op.drop_index(op.f('ix_roster_assignments_id'), table_name='roster_assignments')
    op.drop_index(op.f('ix_roster_assignments_employee_id'), table_name='roster_assignments')
    op.drop_table('roster_assignments')
    op.drop_index(op.f('ix_employee_coverage_id'), table_name='employee_coverage')
    op.drop_index(op.f('ix_employee_coverage_employee_id'), table_name='employee_coverage')
    op.drop_table('employee_coverage')
    op.drop_index(op.f('ix_employees_site_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_codice_fiscale'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_shift_types_id'), table_name='shift_types')
    op.drop_index(op.f('ix_shift_types_code'), table_name='shift_types')
    op.drop_table('shift_types')
    op.drop_index(op.f('ix_job_titles_name'), table_name='job_titles')
    op.drop_index(op.f('ix_job_titles_id'), table_name='job_titles')
    op.drop_table('job_titles')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
